
/**************************************************************
 *	
 *	bump, 8 bit, 11025Hz,
 *	1 channel, 1889 bytes/channel
 *	Total Size: 1 * 1889 + 4 (header) = 1933 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vishakhaholsambre/Documents/cs2261/M05_VishakhaHolsambre/bump.wav
 *	Time-stamp: Fri Apr 26 10:53:35 2019
 *	
 **************************************************************/

#ifndef __BUMPH__
#define __BUMPH__

#define BUMPFREQ 11025
#define BUMPLEN 1889

extern const unsigned char bump[1889];

#endif /* __BUMPH__ */
