
/**************************************************************
 *	
 *	shellsound, 8 bit, 11025Hz,
 *	1 channel, 3316 bytes/channel
 *	Total Size: 1 * 3316 + 4 (header) = 3360 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vishakhaholsambre/Documents/cs2261/M05_VishakhaHolsambre/shellsound.wav
 *	Time-stamp: Fri Apr 26 10:49:03 2019
 *	
 **************************************************************/

#ifndef __SHELLSOUNDH__
#define __SHELLSOUNDH__

#define SHELLSOUNDFREQ 11025
#define SHELLSOUNDLEN 3316

extern const unsigned char shellsound[3316];

#endif /* __SHELLSOUNDH__ */
