
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 581872 bytes/channel
 *	Total Size: 1 * 581872 + 4 (header) = 581916 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vishakhaholsambre/Documents/cs2261/M05_VishakhaHolsambre/TitleSong.wav
 *	Time-stamp: Fri Apr 26 11:32:15 2019
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 581872

extern const unsigned char TitleSong[581872];

#endif /* __TITLESONGH__ */
