
/**************************************************************
 *	
 *	wipe, 8 bit, 11025Hz,
 *	1 channel, 10136 bytes/channel
 *	Total Size: 1 * 10136 + 4 (header) = 10180 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/vishakhaholsambre/Documents/cs2261/M05_VishakhaHolsambre/wipe.wav
 *	Time-stamp: Fri Apr 26 11:23:53 2019
 *	
 **************************************************************/

#ifndef __WIPEH__
#define __WIPEH__

#define WIPEFREQ 11025
#define WIPELEN 10136

extern const unsigned char wipe[10136];

#endif /* __WIPEH__ */
